package com.ecommerce.model;
// Generated Mar 21, 2016 11:49:19 PM by Hibernate Tools 4.3.1.Final

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private long accountId;
	private String email;
	private String userName;
	private String password;
	private String role;
	private String status;

	public Account() {
	}

	public Account(long accountId, String email, String userName, String password, String role, String status) {
		this.accountId = accountId;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.status = status;
	}

	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
