package com.ecommerce.model;
// Generated Mar 21, 2016 11:49:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private long orderId;
	private PaymentMethod paymentMethod;
	private Customer customer;
	private Date orderDate;
	private String orderStatus;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

	public Orders() {
	}

	public Orders(long orderId, PaymentMethod paymentMethod, Customer customer, Date orderDate, String orderStatus) {
		this.orderId = orderId;
		this.paymentMethod = paymentMethod;
		this.customer = customer;
		this.orderDate = orderDate;
		this.orderStatus = orderStatus;
	}

	public Orders(long orderId, PaymentMethod paymentMethod, Customer customer, Date orderDate, String orderStatus,
			Set<OrderItem> orderItems) {
		this.orderId = orderId;
		this.paymentMethod = paymentMethod;
		this.customer = customer;
		this.orderDate = orderDate;
		this.orderStatus = orderStatus;
		this.orderItems = orderItems;
	}

	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	public PaymentMethod getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(PaymentMethod paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

}
