package com.ecommerce.model;
// Generated Mar 21, 2016 11:49:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * PaymentMethod generated by hbm2java
 */
public class PaymentMethod implements java.io.Serializable {

	private long paymentMethodId;
	private String paymentMethodCode;
	private String description;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(long paymentMethodId, String paymentMethodCode, String description) {
		this.paymentMethodId = paymentMethodId;
		this.paymentMethodCode = paymentMethodCode;
		this.description = description;
	}

	public PaymentMethod(long paymentMethodId, String paymentMethodCode, String description, Set<Orders> orderses) {
		this.paymentMethodId = paymentMethodId;
		this.paymentMethodCode = paymentMethodCode;
		this.description = description;
		this.orderses = orderses;
	}

	public long getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(long paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	public String getPaymentMethodCode() {
		return this.paymentMethodCode;
	}

	public void setPaymentMethodCode(String paymentMethodCode) {
		this.paymentMethodCode = paymentMethodCode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
