package com.ecommerce.model;
// Generated Mar 21, 2016 11:49:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProductType generated by hbm2java
 */
public class ProductType implements java.io.Serializable {

	private long productTypeId;
	private String productTypeCode;
	private String productTypeDescription;
	private Set<Product> products = new HashSet<Product>(0);

	public ProductType() {
	}

	public ProductType(long productTypeId, String productTypeCode, String productTypeDescription) {
		this.productTypeId = productTypeId;
		this.productTypeCode = productTypeCode;
		this.productTypeDescription = productTypeDescription;
	}

	public ProductType(long productTypeId, String productTypeCode, String productTypeDescription,
			Set<Product> products) {
		this.productTypeId = productTypeId;
		this.productTypeCode = productTypeCode;
		this.productTypeDescription = productTypeDescription;
		this.products = products;
	}

	public long getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(long productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getProductTypeCode() {
		return this.productTypeCode;
	}

	public void setProductTypeCode(String productTypeCode) {
		this.productTypeCode = productTypeCode;
	}

	public String getProductTypeDescription() {
		return this.productTypeDescription;
	}

	public void setProductTypeDescription(String productTypeDescription) {
		this.productTypeDescription = productTypeDescription;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
