package com.tinhpt;
// Generated Feb 17, 2016 3:56:54 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * DemoUser generated by hbm2java
 */
public class DemoUser implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String phone;
	private String address;

	public DemoUser() {
	}

	public DemoUser(BigDecimal id, String name, String phone, String address) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.address = address;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
